### ISSUE TITLE
Type highlighting in `datatype` constructor

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/ide-vscode#106]
After escaping whatever context the arguments are in initially, everything works.
<img width="231" alt="Screenshot 2021-12-18 at 22 29 04" src="https://user-images.githubusercontent.com/143799/146655924-9e447e01-15ad-4d36-8ccd-3aac929ee94c.png">
`datatype D = D((bool) -> bool)`

**Comment by MikaelMayer** [comment]
What is the expected highlighting? The first bool should be blue, right?

**Comment by fabiomadge** [comment]
`(bool) -> bool` is a type, so it should all be blue, right?

**Comment by MikaelMayer** [comment]
Ok, got it thanks. Will fix it soon.
