### ISSUE TITLE
Versioned installation paths

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/ide-vscode#107]
Currently the VSCode Dafny IDE extension installs a specific version of Dafny.  To use a different version, users have to install Dafny manually and point the extension to that.  It would be nice to make this easier.

I've recently implemented auto-installation for Dafny in Emacs (I'm porting the Emacs mode to use LSP), and in that code I used the following design:

* There is a user setting to specify which version of Dafny to use.  The plugin has a hardcoded list of known versions that it is compatible with, and the value of that setting must be one of these.  It defaults to the highest known version.
* The Dafny binary that the IDE uses is either the one the user specified manually, if any, or the one corresponding to the "version" user setting above.
* If the binary corresponding to the selected version is not installed, the IDE downloads that version of Dafny and saves it to a version-dependent path, which makes it easy to check whether a given version of Dafny is installed.

I experimented with this in Emacs first since changing the VSCode extension wasn't trivial (given that we already had many live installs).  But since we are in fact publishing a new Dafny extension under `dafny-lang`, it might be worth making a similar change to the Dafny VSCode extension, to make it easy for users to switch versions (just change the version and restart the server or IDE).

If we decide to do this, it would be best to do it soon; this way we wouldn't have to worry about backwards compatibility, since we're publishing a new plugin.

**Comment by camrein** [comment]
Providing this feature should be straightforward and probably only [dafnyInstallation.ts](https://github.com/dafny-lang/ide-vscode/blob/master/src/language/dafnyInstallation.ts) (besides the settings).
I see that there is a demand to support multiple Dafny versions from within the language server. In the future, Dafny will support project files making this functionality a bit obsolete. However, the implementation should be no big deal and it still allows configuring the *default* Dafny version. Moreover, depending on when Dafny project files will arrive, it could be a nice feature in combination with VSCode's workspace specific settings in the meantime.

**Comment by cpitclaudel** [comment]
> In the future, Dafny will support project files making this functionality a bit obsolete.

I think most of the code to solve this issue would become part of the project implementation, wouldn't it?

**Comment by camrein** [comment]
I think so. But I believe it might still be useful besides the project feature since it allows people to configure their default Dafny version.
