### ISSUE TITLE
Status bar does not show updates

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/ide-vscode#108]
When I change my program and I know it's busy verifying, the status bar stays empty. If it fails to verify it will change to "Verification failed" when its done verifying.

Logging shows that status bar update messages are coming in from the language server, but the IDE doesn't seem to use them. I'm using the v2.1.1 Dafny extension from dafny-lang.

```
[Trace - 12:15:28 PM] Received notification 'dafny/compilation/status'.
Params: {
    "uri": "file:///Users/rwillems/Documents/Notes/DafnyExamples/temp.dfy",
    "version": 4,
    "status": "VerificationInProgress",
    "message": "SquareRoot2NotRational2"
}


[Trace - 12:15:28 PM] Received notification 'dafny/compilation/status'.
Params: {
    "uri": "file:///Users/rwillems/Documents/Notes/DafnyExamples/temp.dfy",
    "version": 4,
    "status": "VerificationInProgress",
    "message": "GetConstant"
}
```

**Comment by cpitclaudel** [comment]
I'm guessing that's because you're using Dafny from master but the extension from the VSCode store.  The current extension doesn't understand the notifications that the master branch of Dafny sends, so it displays nothing instead.

I guess we could condition these new notifications on an explicit feature tag sent by the client.

**Comment by keyboardDrummer** [comment]
And if we publish a new extension version now, will the status bar be broken unless someone upgrades to the latest Dafny?

**Comment by keyboardDrummer** [comment]
> I guess we could condition these new notifications on an explicit feature tag sent by the client.

I think we should.

Given that new protocol versions are introduced by the server and not the client(s), I think it's better to have the server adapt to the protocol version supported by the client, then ask client(s) to support both the current and upcoming protocol versions of the server.

**Comment by cpitclaudel** [comment]
> And if we publish a new extension version now, will the status bar be broken unless someone upgrades to a new enough Dafny?

No, it shouldn't be.

**Comment by cpitclaudel** [comment]
> I think we should.

OK, I'll prepare a patch
