### ISSUE TITLE
checkDotnetInstallation doesn't distinguish between an incorrect dotnet path and invalid version

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/ide-vscode#112]
Dear Dafny team,

While splunking around during work on #111 I noticed my extension settings were slightly misconfigured: I had misread the description of `dafny.dotnetExecutablePath` to say "the absolute path _to_ dotnet", rather than "the absolute path _of_ dotnet", and I supplied the directory that contains the executable rather than the executable itself.  A simple mistake, easily fixed.  However, in that situation, the `NoCompatibleInstallation` message is still presented to the user, which, at least to my reading, suggests that `dotnet` _was_ found but determined to be an incorrect version, whereas in reality the plugin couldn't find it at all. 

To my mind, the issue is that `hasSupportedDotnetVersion()` eats any exception raised by `execFileAsync()` and simply returns `false` if _anything_ goes wrong, so the UI can't distinguish between an invalid core runtime string being parsed out of running `dotnet` and a failure to run it at all.  I might suggest enriching the return type of `hasSupportedDotnetVersion` for the UI to be able to distinguish this.  Ideally, from the user's perspective, they would be presented different messages in the following cases:

* `dotnet` does not have a valid runtime
* `dotnet` is found but not executable
* `dotnet` is not a file / is missing
* `dotnetExecutable` does not encode a valid path

I imagine the last three can be extracted from the caught exception.  But, I think really, distinguishing between "you haven't given me a valid `dotnet`" versus "`dotnet` is not the right version" would be more than enough.

I have a bunch of spare cycles owing to the holidays, so, if you agree that this is a reasonable enhancement I'm happy to try to take a stab at it.  Thanks!

**Comment by camrein** [comment]
Sorry for the late reply. Thanks a lot for your suggestions.
In my opinion, it would be a great addition to make messages about invalid configurations more descriptive.

**Comment by vesalvojdani** [comment]
But it is a bit unusual to give paths directly to some binary. Could you not make this more clear: "The absolute path of dotnet" -> "The absolute path of the dotnet binary". Ideally, if the path is to a directory, it could check if there is a dotnet binary in there and be happy about it. Other than that, Dafny is miraculously easy to install! :)
