### ISSUE TITLE
When the plugin is `verifying` it does not parse syntax

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#114]
When using Dafny 3.4 and ide upstream I can jump to definitions,
however if verification hangs, then I can not :(

**Comment by keyboardDrummer** [comment]
Can you provide source that reproduces the problem?

**Comment by seebees** [comment]
It may be released to #115 I'l try it some more

**Comment by atomb** [comment]
Is this issue still showing up for you, @seebees?

**Comment by MikaelMayer** [comment]
I don't think this issue is showing up after the recent refactorings.
