### ISSUE TITLE
Verification failures/timeouts can cause verification hangs when Verification Caching Policy is enabled to basic

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#115]
Dafny 3.4 with ide upstream

**Comment by seebees** [comment]
There is no debugging information that I can see

**Comment by cpitclaudel** [comment]
I will look into this.  Trying to get a repro now.

**Comment by seebees** [comment]
I suspect that the best solution will be to treat timeouts as a kind of verification failure.
So whenever results are submitted,
a method can timeout and this is just a failure that appears on the method body.

**Comment by cpitclaudel** [comment]
> I suspect that the best solution will be to treat timeouts as a kind of verification failure.

Yes, the old Dafny server did that.  I have created  dafny-lang/dafny#1710 to track this.

**Comment by MikaelMayer** [comment]
I have the same problem even with no caching.

**Comment by cpitclaudel** [comment]
> I suspect that the best solution will be to treat timeouts as a kind of verification failure.

Done in https://github.com/dafny-lang/dafny/pull/1759
@MikaelMayer also worked on timeouts on the Boogie side.  If the issue pops up again, let's reopen an issue on the Dafny side.
