### ISSUE TITLE
Suggestions for ghost highlighting

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/ide-vscode#126]
I love the new ghost-highlighting feature in the Dafny extension. This feature adds a gray background for statements that are ghost. I have two further suggestions/wishes for this mode.

* I have found that `lemma` bodies are all grayed out. My first thought was that this is due lemmas always being ghost. However, in writing up this Issue, I'm finding that I can't always reproduce the situation. I have now written several `lemma` or `least lemma` declarations without their bodies being turned into gray, and I've also written some `method` bodies where the statements do turn gray (even for assignments to non-ghost out-parameters, which are definitely not ghost statements).

    Here's one example:

    ![image](https://user-images.githubusercontent.com/11763367/151882127-209826fc-3b40-4f5c-9d94-c55948d6628d.png)

    So, my assessment is now that the feature is rather unreliable. I don't understand when it's recomputing this information or what to expect.

* The other issue I have is selected code doesn't show up over the gray ghost highlighting. Usually, when I select some code, it lights up with a blue background. But when the code is displayed as ghost, then the background remains gray even when I select some code. This feels wrong to me as a user. I would like the blue selection highlighting to take priority over the gray ghost highlighting.

**Comment by MikaelMayer** [comment]
Thanks for reporting. I'm in favor of these changes too.

**Comment by camrein** [comment]
Thanks a lot for reporting.
It's definitely undesirable that the ghost information is not reliable, and even shows wrong information.
I'll try to have a look by myself. If anyone wants to give it a try, see below for things that came to my mind that might be helpful.

The decision whether something is marked as ghost or not is straightforward:
https://github.com/dafny-lang/dafny/blob/614425281b4374a47dbc824822728080ff4e5bd8/Source/DafnyLanguageServer/Language/GhostStateDiagnosticCollector.cs#L59-L62

The first thing I'd suggest to avoid marking lemmas as ghost unnecessarily, is to add a simple filter to the visitor implementation. Then we can avoid traversing down inside lemmas (and functions as well) and won't mark ghost statements inside these.

The thing about user interaction with code selection is also very undesirable. It might be possible to resolve this by changing the color of the ghost highlighting to a transparent one:
https://github.com/dafny-lang/ide-vscode/blob/9ff58873f16ceaa032e8478d6109e84e995c8a62/src/ui/ghostDiagnosticsView.ts#L8-L15
