### ISSUE TITLE
Add UI for managing verification tasks

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/ide-vscode#130]
Add UI to the Dafny VSCode extension that enables the following use-cases:
1. Have an overview of what proofs in the project are passing or failing
2. Estimate how long it will take until running verification tasks are completed
3. Identify slow running verification tasks
4. Cancel long running verification tasks so edits can be made before retrying the verification
5. Manually trigger verification for proofs, useful for cases where verification does not trigger automatically.

**Comment by cpitclaudel** [comment]
Is "Select which methods / functions / modules to verify also a goal of this task?" (The title suggested so)

**Comment by keyboardDrummer** [comment]
Replacing with https://github.com/dafny-lang/ide-vscode/issues/154
