### ISSUE TITLE
VSCode sometimes not displaying red underlines for errors

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/ide-vscode#139]
Copied from https://github.com/dafny-lang/dafny/issues/1854 by @emina :

> I've observed that the Dafny VSCode plugin sometimes fails to localize parsing and type errors by underlining them with the red squiggles.
> 
> This behavior is not easy to reproduce, but I'm reporting it here in case others run into it.
> 
> In general, it happens when I'm working on a large file (300+ LOC), and VSCode has been open for a long time (several days).
> 
> Even when the errors aren't localized in the UI, the "Problems" window does list the locations correctly, and they're also listed / found by running the verifier manually.

**Comment by camrein** [comment]
Thanks for filing the GH issue. It's definitely strange that VSCode fails to create the squiggles, especially since VSCode receives the diagnostics since it's displaying it in the problems window. What I'm wondering if it somehow conflicts with the ghost highlighting feature?

**Comment by cpitclaudel** [comment]
Fixed by #141.
