### ISSUE TITLE
VS Code extension hangs on last method

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/ide-vscode#140]
On this commit (https://github.com/robin-aws/libraries/commit/73cc542a337c9ac3233126c6155a1bc56be98e69) when I save the `src/Enumeration/Loopers.dfy` file and trigger verification, I can see the status bar indicator move quickly through each of the methods (love that feature btw!), but it seems to hang on the last method with the message `Verifying _default_Main...`. If I comment out that method and repeat, it hangs on the second-last method (`Example3`).

I suspect what's happening is that a "all verification complete" event is being missed somehow. If I edit the file by adding a space somewhere, for example, then the verification errors show up in the document. This isn't 100% consistent AFAICT though.

I'm using `v2.2.0` of `dafny-lang.ide-vscode` and (~~3f7785fb55a796e6a3e5ced5d315a0ad30001fee of Dafny `master`. I'm pulling down the latest `master` commit but doesn't look likely to fix this.~~) Dafny 3.4.0.

**Comment by MikaelMayer** [comment]
I think this error is now obsolete given all the modifications we have been doing. Happy to reopen if it's still an issue
