### ISSUE TITLE
Feature request: start `DafnyLanguageServer.exe` directly instead of `dotnet.exe DafnyLanguageServer.dll`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/ide-vscode#142]
Starting `dotnet.exe` makes it much harder to locate Dafny processes in e.g. Windows' task manager, or to kill them with `taskkill`.  Would there be a downside to starting DafnyLanguageServer.exe directly?

**Comment by camrein** [comment]
I can't remember the exact error I received. However, I think earlier versions of the Dafny distribution lacked the `DafnyLanguageServer.runtimeconfig.json` and/or `DafnyLanguageServer.deps.json`. This will make the executable fail to run and can be resolved by using `dotnet DafnyLanguageServer.dll` instead.
However, I second the motivation to change to `DafnyLanguageServer.exe` (or possibly any executable). This adds more flexibility, for example, one may use a wrapper such as `wsl` or `docker` to launch the process.

**Comment by MikaelMayer** [comment]
It's now possible to start Dafny.exe directly. so I close this issue
