### ISSUE TITLE
Problems running Dafny on Apple M1 devices

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#146]
On helping someone install VSCode, dotnet 6, and then Dafny, they get the following error:

```
Failed to load /Users/<user>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib, error: dlopen(/Users/<user>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib, 1): no suitable image found.  Did find:
    /Users/<user>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib: mach-o, but wrong architecture
    /Users/<user>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib: mach-o, but wrong architecture
An error occurred while loading required library libhostpolicy.dylib from [/Users/<user>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/]
[Info  - 9:57:07 AM] Connection to server got closed. Server will restart.
(... 5 times)
[Error - 9:57:07 AM] Connection to server got closed. Server will not be restarted.
```

Not sure where this come from

**Comment by camrein** [comment]
Sounds to me like the binary that is downloaded the mac (see the `dylib` extension) is not compatible, see `mach-o, but wrong architecture`.
Dafny ` dafny-?.?.?-x64-osx-10.14.2.zip` is an `x86_64` distro. Does the mac happen to be an ARM / Apple M1 device? Then I suppose we need to distribute suitable OSX images, i.e., execute `dotnet publish` with the respective architecture:

See:
https://github.com/dafny-lang/dafny/blob/b133a187c80e26c25af32bdb6488e3a40e631f41/Scripts/package.py#L137-L143

And:
https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#macos-rids

We'll need to pass the architecture to the `publish` command, for example:
```sh
dotnet publish -r osx-arm64
```

**Comment by camrein** [comment]
> I don't recall whether I did any particular setup, but I might have installed this x64 architecture emulator: https://support.apple.com/en-us/HT211861

I'd prefer a native solution. However, we could add a check to the startup routine of the extension that ensures Rosetta is installed on M1 Macs in the meantime. I believe there will be more and more people using M1s.

**Comment by cpitclaudel** [comment]
The problem isn't installing Rosetta.  @keyboardDrummer, how did you install dotnet? The faulty machine has dotnet installed through homebrew, and `brew install dafny` yields a working `dafny`, whereas downloading our archive and running `dotnet Dafny.dll` causes the crash above.

**Comment by keyboardDrummer** [comment]
I installed dotnet from: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.201-macos-arm64-installer

> downloading our archive and running dotnet Dafny.dll causes the crash above.

Actually I have that too. I wasn't having issues because I was building Dafny from source.

**Comment by cpitclaudel** [comment]
Beautiful, we have a repro! :)

**Comment by rodrilp** [comment]
I have the same problem that @MikaelMayer has in the beginning, is any solution working fine?

**Comment by cpitclaudel** [comment]
For now, the solution is to build locally: clone the repository and run `make exe`.  We are working on a more permanent fix.

**Comment by rodrilp** [comment]
> For now, the solution is to build locally: clone the repository and run `make exe`. We are working on a more permanent fix.

Installing it in this other way, can it be used in the same way in vscode?

**Comment by cpitclaudel** [comment]
> Installing it in this other way, can it be used in the same way in vscode?

Certainly, you just need to change the setting that points visual studio to your Dafny binary.

**Comment by cpitclaudel** [comment]
Moving the discussion to https://github.com/dafny-lang/dafny/issues/1941 in the Dafny repo, since the issue isn't vscode-specific.
