### ISSUE TITLE
Is dafny-vscode extension working for M1 Mac?

### ISSUE THREAD

**Issue by rodrilp** [dafny-lang/ide-vscode#148]
Is it possible to install dafny-vscode in M1 mac?

I installed .NET 6.0, and then the extension of dafny, but I received the following error in the output of the terminal.

`Failed to load /Users/<User>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib, error: dlopen(/Users/<User>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib, 0x0001): tried: '/Users/<User>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
An error occurred while loading required library libhostpolicy.dylib from [/Users/<User>/.vscode/extensions/dafny-lang.ide-vscode-2.3.0/out/resources/3.5.0/dafny/]
[Info  - 8:42:59 PM] Connection to server got closed. Server will restart.`

**Comment by cpitclaudel** [comment]
Thanks for reporting this.  We are tracking the issue [here](https://github.com/dafny-lang/ide-vscode/issues/146).
