### ISSUE TITLE
with comment /* ../* .. */  Dafny appears  to verify falsehood 

### ISSUE THREAD

**Issue by davidstreader** [dafny-lang/ide-vscode#152]
Using VS code with extension  Dafny 0.18.0 and two line file:
/* blah blah /*  blah  */
method  foo() returns (r:bool) { assert true == false; }

The comment is parsed green only until */ But the file is verified.
Removing the second /* the file is not verified.

**Comment by MikaelMayer** [comment]
It's actually a tmLanguage problem.

**Comment by cpitclaudel** [comment]
Two problems, right?  Broken highlighting in the IDE plus broken parsing

**Comment by MikaelMayer** [comment]
If we fixed the highlighting, the parsing does not need to be considered "broken". It could actually be a feature, which makes it possible to comment out the rest of a file without having to add a closing comment

**Comment by cpitclaudel** [comment]
Fair, but at least lets give a warning?

**Comment by MikaelMayer** [comment]
That's fair.

**Comment by davidcok** [comment]
Command-line tools do not see highlighting -- I think an unclosed comment should be warned about.

**Comment by MikaelMayer** [comment]
Can you please open a new issue instead of reopening this one? No one should edit Dafny files without a proper syntax highlighter.
Also, I'm not sure I want an unclosed comment to be warned about. It's part of the design, and makes it possible to comment out the rest of a file easily.

**Comment by davidcok** [comment]
For me, not warning about an unclosed block comment is a UI mistake rather than a feature -- it too easily leads to confusion from typos, especially with our unusual feature of nested comments. But I'll leave the matter be -- I won't start an issue opening/closing battle.
