### ISSUE TITLE
Display the status of declarations (methods, subset types, etc) that require verification

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/ide-vscode#154]
Use the VSCoded testing API to show a list view of declarations from the Dafny programs that require verification. These are declarations like: methods, function, subset types, newtypes, datatypes, iterators, constants.

For each item in the list, show its current status:
- Stale: should be run, but is not queued to run (can occur when verify on save is on)
- Queued: waiting for resources to run
- Running
- Verified: completed without errors
- Failed: completed with verification errors

For running items, show how long they have been running. For verified or failed items, show how long they took to complete after they started running.

### Use-cases

(Discover failing proofs) Within using the CLI or opening all of their source code files, the user will be able to see which proofs in their Dafny program are failing.

(Identify slow running proofs) One user complaint we’ve received is that verification in the IDE sometimes becomes unresponsive. One possible cause of this may be a proof that requires a long time to verify. The customer should know which proof this is so they can change the proof and make it faster to verify, and they should be able to cancel the slow running verification after patching the proof.

(Identify resources constraints) If declarations are often queued to be verified, the customers might want to configure Dafny's IDE to use more cores.

(Estimate time to verify) If a user makes a change to their Dafny program that affects the verification of multiple proofs, and verification of those proofs is running, we would like to enable the customer to estimate how long until verification for all proofs is completed, by showing them all proofs that still need to verify, how many are verifying in parallel, and how long verification of these proofs took previously.

### Dependent issues
- https://github.com/dafny-lang/ide-vscode/issues/97
- https://github.com/dafny-lang/ide-vscode/issues/96

**Comment by keyboardDrummer** [comment]
Related PR: https://github.com/dafny-lang/dafny/pull/2094/files#

**Comment by MikaelMayer** [comment]
I think this is now fixed, thanks !
