### ISSUE TITLE
Syntax highlighting, bracket matching etc doesn't respect nested comments

### ISSUE THREAD

**Issue by cdisselkoen** [dafny-lang/ide-vscode#157]
Dafny `/*` and `*/` comments nest, but the syntax highlighting, bracket matching, etc don't recognize this.  For instance,
```
  function foo(i: nat): nat {
    /* comment
    /* nested comment
    */ }
    */
  }
```
VSCode syntax highlighting doesn't properly color the `}` on line 4 as a comment.  Furthermore, if I put the cursor on the `{`, VSCode highlights the `}` on line 4 as the matching brace, while Dafny actually considers the `}` on line 6 to be the matching brace.  (And, if I use the Vim extension keybind `%` to jump to the matching brace, it also jumps to the wrong brace.)  

This leads to counterintuitive parse errors: suppose you accidentally omitted the final `}`, Dafny will complain about needing a `}`, but VSCode will tell you everything is matched.  Or, if you accidentally have `/*` inside a comment, Dafny will consider the rest of the file commented out, while in VSCode everything looks fine.

**Comment by MikaelMayer** [comment]
It's time for an upgrade ! I just pushed a PR to fix that pesky problem.

**Comment by cpitclaudel** [comment]
![image](https://user-images.githubusercontent.com/8181630/169369859-4e49d560-7948-45fd-a362-807b36f9b92c.png)

😌
