### ISSUE TITLE
Dafny extension spawns endless instances of Z3. 

### ISSUE THREAD

**Issue by hath995** [dafny-lang/ide-vscode#168]
Hello,
I'm really enjoying learning Dafny and the plugin is essential so great work so far!

 I keep running into the following issue. 
![z3explosion](https://user-images.githubusercontent.com/381037/171406588-ac7b3be4-40b2-4569-8ab4-dd1a3e97e4f3.png)
After using dafny for a while on both mac and windows using extension version Dafny v2.4.0, there is an explosion of z3 processes created and they never seem to close. Eventually, it seems like it overwhelms my system and I am forced to close and restart vscode. Sometimes on mac even after I exit vscode I need to manually kill dotnet and z3.

**Comment by atomb** [comment]
If you look at the Dafny version on the right side of the VSCode status bar, what does it say? The current version is 3.6.0.40511. We did have some bugs in older versions related to cleaning up old processes, but as far as I know they've been fixed in the latest version.

**Comment by hath995** [comment]
That is the version I see in my editor.

**Comment by keyboardDrummer** [comment]
Reproduction as reported by @MikaelMayer:

Copy the following code and 
```
class Test {
    var a: nat
    var b: nat
    var c: nat

    predicate Valid()
        reads this
    {
        && a < b
        && b < c
    }

    method Foo()
        requires Valid()
        ensures Valid()
        modifies this
    {
        c := 10;
    }
}
```

put it in VSCode. Look at the task manager, it has one dangling z3 process. Add newlines in this file, wait, every newline you add, one more z3 process is created

**Comment by hath995** [comment]
I can confirm the reproduction steps work for me as well.
