### ISSUE TITLE
Dafny installation failed > Error: Command failed: make exe

### ISSUE THREAD

**Issue by lzp0409** [dafny-lang/ide-vscode#171]
starting Dafny installation
deleting previous Dafny installation at /Users/me/.vscode/extensions/dafny-lang.ide-vscode-2.4.0/out/resources/3.6.0
downloading Dafny from https://github.com/dafny-lang/dafny/releases/download/v3.6.0/dafny-3.6.0-x64-osx-10.14.2.zip
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
extracting Dafny to /Users/me/.vscode/extensions/dafny-lang.ide-vscode-2.4.0/out/resources/3.6.0
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Dafny installation completed
Found a non-supported architecture OSX:arm64. Going to install from source and replace the automated installation.
Installing Dafny from source in /Users/me/.vscode/extensions/dafny-lang.ide-vscode-2.4.0/out/resources/3.6.0/custom/arm64.

Executing: brew install dotnet-sdk
Executing: git clone --recurse-submodules https://github.com/dafny-lang/dafny.git
Executing: git fetch --all --tags
Executing: git checkout v3.6.0
Executing: make exe
Dafny installation failed:
> Error: Command failed: make exe
make: *** [exe] Error 1

**Comment by seebees** [comment]
This should have been fixed by #287
This was on an M1 mac right?

**Comment by keyboardDrummer** [comment]
We're hoping to build Dafny for M* macs as well, which should resolve this issue: https://github.com/dafny-lang/dafny/issues/2889

**Comment by MikaelMayer** [comment]
This was normally fixed as we publish artifacts for this platform now.
