### ISSUE TITLE
Publish the extension to Open VSX

### ISSUE THREAD

**Issue by filiptronicek** [dafny-lang/ide-vscode#172]
Hello there!
Please publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [OpenVSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is OpenVSX? Why does it exist?

OpenVSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/) based IDEs, and so on.

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the command `ovsx publish` to publish your plugin. See this example from RedHat publishes their Java extension: [redhat-developer/vscode-java@ff51dbf/Jenkinsfile#L73-L82](https://github.com/redhat-developer/vscode-java/blob/5d4f8d58b8e919534800ca7bc41e8513c288f573/Jenkinsfile#L78-L82)
You can also find [an example PR](https://github.com/PeterWone/vsc-print/pull/121) that contributes a release GitHub Action which publishes to GitHub, MS and OpenVSX at the same time. I would like to contribute an update to https://github.com/dafny-lang/ide-vscode/blob/master/.github/workflows/ci.yaml if it's wanted in order to enable publishing.

**Comment by MikaelMayer** [comment]
> I would like to contribute an update to https://github.com/dafny-lang/ide-vscode/blob/master/.github/workflows/ci.yaml if it's wanted in order to enable publishing.

Yes feel free to suggest a PR for that, I can review it !

**Comment by keyboardDrummer** [comment]
> I would like to contribute an update to https://github.com/dafny-lang/ide-vscode/blob/master/.github/workflows/ci.yaml if it's wanted in order to enable publishing

That would be great. We'd love to be in the OpenVSX marketplace.

**Comment by turbotimon** [comment]
any news on that?

**Comment by turbotimon** [comment]
Publishing the Dafny Extension in parallel to OpenVSX would benefit the Dafny community. It should be easy and can be done with these two steps:

1. Claiming the namespace “dafny-lang” (can be different) on [open-vsx.org](open-vsx.org) and get a token ([how to](https://github.com/eclipse/openvsx/wiki/Namespace-Access#how-to-claim-a-namespace))

1. Modifying the Github pipeline to publish it to OpenVSX (very similar as already been done for VS Marketplace)

@RustanLeino @keyboardDrummer I would be happy to help with that and sende a PR, however, especially the first step has to be done from a member of https://github.com/dafny-lang to prove legitimacy (or you add me temporarily, I work with the initial developers of the extension at OST).

**Comment by turbotimon** [comment]
@RustanLeino @keyboardDrummer is there any news on this? Let me know if I can help

**Comment by keyboardDrummer** [comment]
Sorry for the lack of action on our side. I've created the open-vsx namespace and a request to authorize it.

**Comment by keyboardDrummer** [comment]
Published on OpenVSX now: https://open-vsx.org/extension/dafny-lang/ide-vscode

**Comment by turbotimon** [comment]
Very nice, thanks!
