### ISSUE TITLE
Squigly lines don't disappear for Veryfication Caching Policy = basic or advanced

### ISSUE THREAD

**Issue by xtrm0** [dafny-lang/ide-vscode#187]
If:
1) option dafny.verificationCachingPolicy is set to anything other than none
2) a file has been verified once
3) some change happens on the file triggering verification again

Then the green squigly lines (meaning that the verification for those lines is running again and hasn't finished) is not disapearing. This is a bit confusing. 

Example (First few lines are both squiggly and opaque light green because they were both cached (so the squigly lines failed to disapear) and verified, last few lines are opaque light green because they were verified just now, and so the squigly lines disapeared)
![image](https://user-images.githubusercontent.com/1348329/176093866-694ed626-70a9-476c-8f7d-22a78d0062c6.png)

Is this intended behavior, if so, what is the meaning of the light green squigly lines?

**Comment by MikaelMayer** [comment]
Thank you very much for spotting it ! It is not intended behavior. It's a bug. I just fixed it.
