### ISSUE TITLE
"Show/Hide CounterExample" to toggle rather than be seperate

### ISSUE THREAD

**Issue by codyroux** [dafny-lang/ide-vscode#188]
Rather than having 2 options `Show CounterExample` and `Hide CounterExample`, with different shortcuts, one could have a single option `Show/Hide CounterExample` which simply toggles the state (or even better, the toggle state would show up in the display, so that `Show CounterExample` would become `Hide CounterExample`).

Very minor quibble, but I'd also rather have it be "Counter Example" than "CounterExample", unless that's the exact name of the CLI option.

**Comment by keyboardDrummer** [comment]
`counterexample` is a single word, so I'd suggest changing `CounterExample` to `Counterexample`

**Comment by codyroux** [comment]
that's a fair point!
