### ISSUE TITLE
Multi-line underlines are truncated

### ISSUE THREAD

**Issue by codyroux** [dafny-lang/ide-vscode#189]
As the attached image shows, a multi-line refuted assert only underlines the first line, which can be confusing.
<img width="172" alt="multi_line_squiggle" src="https://user-images.githubusercontent.com/4193616/176267507-9bf32ad9-7d55-4003-8043-ea25b7848032.PNG">

**Comment by MikaelMayer** [comment]
Thanks for reporting. I've hit this as well. It's a bug that ought to be fixed

**Comment by keyboardDrummer** [comment]
Not really important, but if this issue also occurs on the CLI it would be better to have it live in `dafny-lang/dafny`

**Comment by MikaelMayer** [comment]
It would occur on the CLI only if `/showSnippets:1` and if https://github.com/dafny-lang/dafny/pull/2202 is merge, so it's not a problem for now.
