### ISSUE TITLE
"Dafny: Compile" command uses incorrect filename

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/ide-vscode#204]
When I run the "Dafny: Compile" command from the Command Palette, the extension runs this command in the Terminal pane:

```
$ "/usr/local/share/dotnet/dotnet" "[object Promise]" "/Users/alexchew/wp/tmp/dafny-test/empty/Empty.dfy" /compile:0 /vcsCores:2 /trace /timeLimit:20 /out:bin/Empty
```

(Empty.dfy is just an empty file I created for testing this, but I see the same behavior on other Dafny files that previously verified under older versions of VS Code / Dafny / ide-vscode.)

---

### VS Code
Version: 1.69.1 (Universal)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:51.333Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

### Dafny/IDE
Compiler: 3.7.2.40713
Language Server: 3.7.2.40713
Extension: 2.6.0

**Comment by MikaelMayer** [comment]
Ooops thanks for reporting. Let me look at that.
