### ISSUE TITLE
`This postcondition holds` and `A postcondition might not hold` on the same postcondition

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/ide-vscode#210]
Example input:

```
predicate f(x: int) {
  x > 0
}

predicate T(x: int, y: bool) {
  f(x) && y
}

method M()
  ensures T(-2, true)
{
}
```

![image](https://user-images.githubusercontent.com/8181630/177882188-81d5f6f6-3b1c-4db1-a172-00056f19b1a0.png)

**Comment by MikaelMayer** [comment]
This will be fixed by https://github.com/dafny-lang/dafny/pull/3282
See the result here:
![image](https://user-images.githubusercontent.com/3601079/210602670-d01e76ac-1fe4-47ed-93e1-d1a4f0268f8e.png)
