### ISSUE TITLE
Installation without dotnet

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/ide-vscode#220]
The other day I was getting started on a fresh loaner Mac and tried installing Dafny through the extension. When given the download link I selected the wrong binary, not including ASP.NET Core Runtime 5.0 or 6.0. Can we include that information in the prompt before sending the user to select one unprepared?

**Comment by MikaelMayer** [comment]
Do you mean, in this message?
What other message would have helped?
https://github.com/dafny-lang/ide-vscode/blob/879befdcb3161d2c42f010cfca303d0220e26306/src/ui/messages.ts#L29-L32

**Comment by MikaelMayer** [comment]
What is the ASP.NET requirement? I'm not sure I follow. Anything you remember could be helpful.

**Comment by fabiomadge** [comment]
[It](https://en.wikipedia.org/wiki/ASP.NET) seem to be some kind of .NET framework which we seemingly depend on. Not all runtime bundles come with it. I think the best call for us would be recommending to install the .NET SDK, which also bundles it and is probably a dependency for running C# code anyway.

**Comment by MikaelMayer** [comment]
Can you suggest an edit?

**Comment by fabiomadge** [comment]
Tried it in #227.
