### ISSUE TITLE
Information sent by the language server not correctly displayed

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#236]
I just gave a try to the new IDE extension pointing to the latest version of Dafny, with verification on change.

I open an untitled file and then I see in the logs

```
[Trace - 08:42:21] Received notification 'dafny/compilation/status'.
Params: {
    "uri": "untitled:Untitled-1",
    "version": 1,
    "status": "VerificationStarted",
    "message": null
}


[Trace - 08:42:21] Received notification 'dafny/compilation/status'.
Params: {
    "uri": "untitled:Untitled-1",
    "version": 1,
    "status": "VerificationSucceeded",
    "message": null
}
```

However, the status message is still:
![image](https://user-images.githubusercontent.com/3601079/182389986-8c2ea64b-8f60-4478-b169-daa2b38cd58b.png)

And when write a simple method such as

```dafny
lemma Test() {

}
```

The gutter is not updated, although the log witnesses that it received three green gutter icons.
When I save the file afterwards, same.
It works on other files that existed before. But reloading the window does not change anything for that new file, it stays the same.

**Comment by keyboardDrummer** [comment]
This is caused by a bug related to unsaved files. Resolved here: https://github.com/dafny-lang/ide-vscode/pull/234
