### ISSUE TITLE
Verification management UI overlaps with gutter icons

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#237]
I managed to get to the following state while working with verification management UI:

![image](https://user-images.githubusercontent.com/3601079/182391411-25b1c245-e587-4610-8258-3760a55f7958.png)

**Comment by keyboardDrummer** [comment]
Any idea of how to reproduce? Can you also reproduce while using https://github.com/dafny-lang/ide-vscode/pull/234 ?

**Comment by MikaelMayer** [comment]
To reproduce, even using #234 , enter the code

```dafny
method test(a: int) {
  assert true;
}
```

Then place the caret at the beginning of the file and press ENTER twice very quickly. Try a few times. You should see this:
![image](https://user-images.githubusercontent.com/3601079/182428469-78033b80-8f6e-4e3e-a07f-7791ae168470.png)

**Comment by MikaelMayer** [comment]
Version with failure:

![image](https://user-images.githubusercontent.com/3601079/182428578-b37f70c6-20f4-4af5-95ef-f02db53865bb.png)
