### ISSUE TITLE
VSCode new version bugs

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#247]
VSCode version 2.7.0 seems broken (again)
![image](https://user-images.githubusercontent.com/3601079/183507015-82b44241-c9c2-47de-870e-6bb79cdd6014.png)
It stays like this for a long time, never updates. If I modify the code, it's frozen

I get also four z3 processes that never terminate.
![image](https://user-images.githubusercontent.com/3601079/183507325-dc6633d1-8736-45d1-a849-f1bbd23e447f.png)

When I restart, it works again, but then very quickly it no longer respond.
Gutter icons are regularly broken as well.

![image](https://user-images.githubusercontent.com/3601079/183508944-fd6efa5a-91d5-48d5-b6b9-df14b6bdd27b.png)

**Comment by keyboardDrummer** [comment]
Any reproduction?

**Comment by MikaelMayer** [comment]
```
function {:fuel 100} fib(n: int): int {
  if n <= 1 then 1 else fib(n - 1) + fib(n - 2)
}

//method Main() {
//  assert true;
//}

method test1() {
  assert fib(100000) != 2;
}
method test2() {
  assert fib(100000) != 2;
}
method test3() {
  assert fib(100000) != 2;
}
method test4() {
  assert fib(100000) != 2;
}
```

And then uncomment the main method.

**Comment by keyboardDrummer** [comment]
I've done the above but it looks good for me. Using Dafny nightly and master ide-vscode.

**Comment by MikaelMayer** [comment]
Have you tried disabling caching, and manually put the number of cores to 4?

> With the latest VSCode version, 2.7.0, using the latest stable Dafny, this issue doesn't seem to be applicable since it doesn't use the verification as tests UI, which require Dafny >=3.8.0

Yes, latest stable Dafny does not have this issue.

**Comment by keyboardDrummer** [comment]
Still can't reproduce an issue
