### ISSUE TITLE
New test extension does not display parser and resolution errors anymore in the gutter

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#259]
If deactivate the option "verification as tests"
![image](https://user-images.githubusercontent.com/3601079/187295000-96f974a3-20b4-4e88-a2d9-991eee2fb3fa.png)

If activate the option "verification as tests"
![image](https://user-images.githubusercontent.com/3601079/187294906-7847d2f7-129e-47cb-81dd-94d3d1ac33e8.png)

The icon is no longer displayed and the gutter is no longer grayed out.
The problem comes from the extension as the server correctly sends out the correct gutter icons in both case.

**Comment by keyboardDrummer** [comment]
Any ideas @MikaelMayer ? I'm not so familiar with the gutter icon generation logic.

**Comment by MikaelMayer** [comment]
I just looked at it, it looks like this promise from  at the end of this code is never resolved:

[```
const ranges = await this.getRangesOfLineStatus(params);
```](https://github.com/dafny-lang/ide-vscode/blob/dfaa18632dceb4ed96299d2545e70ed5ead4ee09/src/ui/verificationGutterStatusView.ts#L309-L315)

Any idea why?
