### ISSUE TITLE
Previous Dafny version text input

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#266]
I can see that having _every_ version available in the IDE config dropdown may be too much.
But if there was a way to enter a custom version,
then we could be more aggressive about what versions
appear in the dropdown.

**Comment by seebees** [comment]
It also might be nice to add a `nightly` tag
to get the absolutely most recent version for testing.

**Comment by keyboardDrummer** [comment]
> It also might be nice to add a `nightly` tag to get the absolutely most recent version for testing.

"latest nightly" is already there, isn't it?

**Comment by MikaelMayer** [comment]
I'll close this mechanism as the way to select a version slightly changed. Now you can select "custom" from the list of versions, it's just that you'll have to download Dafny yourself.
We will maintain previous Dafny versions manually and not remove them immediately for at least the last minor version (so you'll still have 3.10.0, 3.10.1, 3.10.2.... etc.), but we will gradually remove patches from previous release versions.
