### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by rance-cleaveland** [dafny-lang/ide-vscode#272]
Failing code
------------

```dafny
method Abs(x: int) returns (y: int)
    ensures 0 <= y
{
    if (x < 0) {
        y := -x;
    }
    else {
        y := x;
    }
}
```

Steps to reproduce the issue
----------------------------

* Dafny version: 3.8.1.40901
* Dafny VSCode extension version: 2.8.2
* 

Expected behavior
-----------------

Expect verification to terminate

Actual behavior
---------------
After 30 mins. there is still the message in the VSC footer "Verified 0/1, verifying Abs" followed by "Running tests".  I killed a restarted once ... still no luck.

FWIW this is a fresh install of dafny.  I want to use it in my class and want to debug the installation procedure before unleashing my students on it.

**Comment by keyboardDrummer** [comment]
This behaves well on my machine. What happens if you run this using the Dafny CLI? 

Could you check if all Dafny programs do not finish verification in your Dafny IDE?

Do you happen to use an M1 machine, or did your IDE happen to report installing Dafny from source?

**Comment by rance-cleaveland** [comment]
It seems to terminate on the CLI.  At least, the terminal window within VS Code reports success.  The IDE never updates, however.

I installed Dafny using the instructions on github:  I installed the VS Code extension (.NET version is 6.0+).  When I opened my first Dafny program I was prompted to install Dafny; this completed successfully.  Every program I try, though, has the IDE problem I mentioned above.

I'm including a screenshot of the IDE in case this is helpful.


![image](https://user-images.githubusercontent.com/67478662/192303173-9006b66f-fd67-4115-8e2f-db8ca05ab103.png)

**Comment by rance-cleaveland** [comment]
Just to be clear:  the Terminal window suggest the verifier finished (as expected), but the footer of the IDE says "Verified 0/1", and the progress wheel next to "Running tests..." runs indefinitely.

**Comment by rance-cleaveland** [comment]
I have done a little more digging, with someone more knowledgeable about the Dafny implementation than I, and the problem appears to be in DafnyLanguageServer.dll.  Dafny.dll appears to work correctly.  One issue that may be relevant:  my path for DafnyLanguageServer.dll (and Dafny.dll) contains a space in one of the directory names (my home directory).  I noticed this seemed to confuse DafnyLanguageServer 3.8.0 when I back out to this version to see if that fixed anything.

**Comment by MikaelMayer** [comment]
After discussing with @rance-cleaveland  offline, and adding the option `"dafny-vscode.trace.server": "verbose"` in the settings.json file of vscode, we identified the problem: @rance-cleaveland 's username had a space in it, and that made Dafny unable to figure out where Z3 is (there was an error which truncated the full path at the space).
