### ISSUE TITLE
Generic function names not highlighted

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/ide-vscode#274]
Dafny-VSCode highlights the name of a function in a declaration such as `function method f(t: int)`
but not in a generic declaration like `function method f<T>(t: T)`

**Comment by MikaelMayer** [comment]
Can you please share a specific example? I can't reproduce the problem
![image](https://user-images.githubusercontent.com/3601079/193070503-6328eba3-59ed-4b0f-9ebb-80fe1c63ac92.png)

**Comment by MikaelMayer** [comment]
Closing as we don't have  a repro for now. Feel free to reopen if you have one.
