### ISSUE TITLE
Keep compiler settings and language server setting in sync

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/ide-vscode#276]
I spent several hours getting more and more confused until I realized that I had to set /functionSyntax:4 in two places: the compiler settings and the LS settings. It seems this option needs to be the same in both places, and there may be other such options as well.

I suggest a common set of settings for these, or one place where they are set by toggles -- or something to avoid this kind of user confusion.

PS. It appears that changing the LS settings requires a restart -- if so, a warning could be placed in the preferences panel

PPS. Does the language server support /functionSyntax:4 ?

**Comment by keyboardDrummer** [comment]
Step to take:

- Introduce the `dafny server` command that allows starting the language server with the same options as the Dafny CLI.
- Introduce a project file that the language server will use as configuration, where /functionSyntax:4 can be specified, and that the CLI can ingest.

**Comment by MikaelMayer** [comment]
Closed with the recent development of @keyboardDrummer  and the release of the new Dafny and extension version
