### ISSUE TITLE
Use already-running language server?

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/ide-vscode#302]
Hi all,

I'm in the process of trying to debug a Dafny issue, and I'd like to set a breakpoint in the language server in order to diagnose it.  However, it seems like by default the IDE extension always spawns an instance of the DafnyLanguage Server:

```
➜  dafny git:(master) ✗ ps aux | grep Language
ntaylor          20885   0.5  0.7 411759600 115632   ??  S     3:11PM   0:02.58 /Users/ntaylor/Downloads/aspnetcore-runtime-6.0.1-osx-arm64/dotnet /Users/ntaylor/code/dafny/Binaries/DafnyLanguageServer.dll --documents:verify=onchange --verifier:timelimit=20 --verifier:verifySnapshots=0 --verifier:vcscores=0 --ghost:markStatements=true --verifier:gutterStatus=true
ntaylor          20569   0.0  0.1 411468800  24512 s007  S+    3:09PM   0:00.67 /Users/ntaylor/code/dafny/Binaries/DafnyLanguageServer
ntaylor          20908   0.0  0.0 408103312   1360 s005  S+    3:12PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox Language
➜  dafny git:(master) ✗
```

What I'd like to do is have the extension be able to "attach itself" to, for instance, the already-spawned PID 20569, which is running under Rider and has breakpoint set.  Is there a way to do this?  If not, broadly, how does one go about debugging issues in a running languge server?

Thanks!
Nathan

**Comment by MikaelMayer** [comment]
In Rider, Run ... > Attach to process > select DafnyLanguageServer.dll

**Comment by dijkstracula** [comment]
Ah, of course, I should have thought of targeting the already-running one.  Thanks, Mikael!
