### ISSUE TITLE
No error message after a few indirections

### ISSUE THREAD

**Issue by ajewellamz** [dafny-lang/ide-vscode#306]
File "bbb.dfy" has one line : include "./ccc.dfy"
File "ccc.dfy" has one line : include "./ddd.dfy"
File "ddd.dfy" has one line : include "./does_not_exist.dfy" // i.e. a file that does not exist

Viewing ddd.dfy, VC properly underlines the include
Viewing ccc.dfy, VC properly underlines the include
Viewing bbb.dfy, VC DOES NOT underline the include

If only bbb.dfy is open, VC says “No problems have been detected in the workspace.”
but also “Parsing failed” at the bottom, with no indication of what it might have failed to parse.
and nothing underlined to indicate a problem

VC should underline the include in bbb.dfy

**Comment by keyboardDrummer** [comment]
Closing because this has been resolved
