### ISSUE TITLE
Setting to set the verifier arguments

### ISSUE THREAD

**Issue by jorge-jbs** [dafny-lang/ide-vscode#307]
Now it is possible to set the arguments passed to the compiler or the language server, but to my knowledge I cannot set the arguments passed to Dafny when it verifies the file (every time I save). Is there currently a way to do this that I'm missing?

**Comment by jorge-jbs** [comment]
Right now I need to set `allocated` to a different value but I think that a more general setting would be more useful.

**Comment by MikaelMayer** [comment]
This is now fixed with the last release of VSCode plugin and Dafny 3.10. You can now specify the same options as the dafny CLI in the settings
