### ISSUE TITLE
The "onsave" setting queues "onchange" events

### ISSUE THREAD

**Issue by fpoli** [dafny-lang/ide-vscode#31]
When I configure the extension to verify "onsave", it seems that the IDE queues all "onchange" events and releases them as soon as I save the file. The server then verifies all changes one by one, reporting errors in the document for the latest change from the queue that it managed to verify so far. Many of such error messages are reported misaligned, because the content of the document is no longer equal to the version that the server verified.

I'm using the Dafny IDE from Mac.

**Comment by camrein** [comment]
Just to clarify: Your VSCode/Extension is busy with the verification and queues all succeeding changes you're doing in the meantime without immediate feedback? As soon as the verification is complete, you'll get the error messages of the changes you've applied after the verification was run?

**Comment by fpoli** [comment]
What I observe is that the IDE keeps showing misaligned error messages, changing error messages every fraction of a second, until the extension reports valid error messages for the latest version of the document. So, I think that the extension reports error messages for all the intermediate versions of the document that are in the queue.

**Comment by camrein** [comment]
Resolved with https://github.com/dafny-lang/dafny/pull/1456
