### ISSUE TITLE
Unable to get the VSCode extension running on M1 Mac

### ISSUE THREAD

**Issue by BhuvanVankadari** [dafny-lang/ide-vscode#353]
Hey,
I have been trying to get the extension running on my M1 Mac and I constantly get the error on the VSCode Terminal `Failed to load /Users/name/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/libhostpolicy.dylib, error: dlopen(/Users/name/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/libhostpolicy.dylib, 0x0001): tried: '/Users/name/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/name/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/libhostpolicy.dylib' (no such file), '/Users/name/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
An error occurred while loading required library libhostpolicy.dylib from [/Users/name/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/]`

**Comment by atomb** [comment]
Do you happen to have a record of the console output printed while the extension installed Dafny? It _should_ have downloaded an `arm64` version, but somehow it didn't.

**Comment by BhuvanVankadari** [comment]
How exactly could I get this? I tried to uninstall the extension and re-install it but it only shows the above error in the output.

**Comment by atomb** [comment]
IIRC, you might see it if you open the console pane before installing the extension.

I have a machine around here with an M1 processor, so I'm going to give it a try, myself, too.

**Comment by atomb** [comment]
Hmm. When I loaded VS Code on my M1 laptop, it had an outdated extension so needed to reload to update. Once I did that, it noticed that a new Dafny version was available and downloaded that, automatically popping up a console pane to show progress. The contents, in my case, looked like this:

```
Standalone language server installation started.
deleting previous Dafny installation at /Users/atomb/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github
downloading Dafny from https://github.com/dafny-lang/dafny/releases/download/v3.11.0/dafny-3.11.0-arm64-osx-11.0.zip
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
extracting Dafny to /Users/atomb/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Standalone language server installation completed.
Language server: {"command":"/opt/homebrew/bin/dotnet","args":["/Users/atomb/.vscode/extensions/dafny-lang.ide-vscode-3.0.4/out/resources/3.11.0/github/dafny/Dafny.dll","server","--verify-on:Save","--verification-time-limit:15","--cache-verification=0","--cores:6","--notify-ghostness:true","--notify-line-verification-status:true"]}
Dafny is ready
```

I wonder whether there's something weird about your environment that causes the extension to mis-detect what platform you're using.

**Comment by atomb** [comment]
Could you go to the "Code > About Visual Studio Code" menu item, click the "Copy" button, and paste the output here? I'm wondering whether VS Code is an x64 build, or something like that.

**Comment by BhuvanVankadari** [comment]
I just checked the version, and for some reason it was the x644 build, just uninstalled it and installed the arm64 version and it worked like a charm! Thank you so much, you were of great heelp :D
