### ISSUE TITLE
Attempting to use Dafny 3.9.1 on M1 Mac fails

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/ide-vscode#367]
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/salkeldr/.vscode/extensions/dafny-lang.ide-vscode-3.0.8/out/resources/3.9.1/custom/arm64/dafny/Binaries/DafnyLanguageServer.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[Info  - 8:50:04 AM] Connection to server got closed. Server will restart.
```

We likely changed the logic to work with newer versions that include an arm64 distribution? What should happen is a graceful fallback to building from source, or at worst a message that this isn't supported.

**Comment by keyboardDrummer** [comment]
Seems like your from source installation is corrupt. Could you check what's in `/Users/salkeldr/.vscode/extensions/dafny-lang.ide-vscode-3.0.8/out/resources/3.9.1/custom/arm64/dafny/Binaries/` ?  There's a check for the existence of that directory, and if it passes it'll consider the from source installation to be available and try to start `DafnyLanguageServer.dll` from there.

**Comment by robin-aws** [comment]
Thanks, clearing out that `resources` directory seems to have fixed it.
