### ISSUE TITLE
Non-ghost code displayed as ghost

### ISSUE THREAD

**Issue by jtristan** [dafny-lang/ide-vscode#374]
<img width="274" alt="Screenshot 2023-03-08 at 2 38 43 PM" src="https://user-images.githubusercontent.com/729989/223826261-c2ae177e-ec5c-4fb4-8d99-49bc2d5cd956.png">

**Comment by MikaelMayer** [comment]
Related to https://github.com/dafny-lang/ide-vscode/issues/372
