### ISSUE TITLE
Verification: never does not apply when running

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/ide-vscode#379]
If you switch "verify:never" in the options and then right-click a Dafny program, run, it does not add the option --no-verify as one would expect.

**Comment by keyboardDrummer** [comment]
Is that really what you'd expect? Isn't `verify:never` about when the IDE verifies your code while you're editing?

I think we should use VSCode's task APIs to let users run/build/translate their Dafny project: https://code.visualstudio.com/docs/editor/tasks

It will allow users to customize the various tasks using a `tasks.json` file.

**Comment by MikaelMayer** [comment]
You're right, it's about automatic verification. I clarified it in
https://github.com/dafny-lang/ide-vscode/pull/397
