### ISSUE TITLE
My language server download failed ?

### ISSUE THREAD

**Issue by Aaron-clou** [dafny-lang/ide-vscode#38]
My first time use VScode to compile Dafny by following[https://github.com/dafny-lang/dafny/wiki/INSTALL#compiling-dafny](url)
[https://marketplace.visualstudio.com/items?itemName=correctnessLab.dafny-vscode](url)
Install Dafny extension,install Netcore5.0 manually,everthing fine,then last step **install language server** got wrong
![snapshot](https://user-images.githubusercontent.com/68632073/127964056-528a6ad7-8069-4733-8d84-e65670fdd85f.png)
**As you see,nothing change,nothing download,I wait an hour and still like this.**
I try uninstall Dafny extension and install again, or change internet ,but don‘t work
so when I try to compile it ,it said``` command"dafny.compile"not found```
I really want to know how to solve these , how to correctly compile dafny on vscode
thanks in advance!

**Comment by camrein** [comment]
Sorry for the late reply.
That's some strange behavior. If they're was a download/extraction/etc. error, the extension would inform you. It might be that download is exceptionally slow. I have observed something similar when running a virtual machine behind my 10GBit/s port - the download was lower than 1kb/s, although I have an internet speed of 1GBit/s. It was reasoned to some driver issue.
One quick solution would be downloading the language server and compiler manually from [here](https://github.com/dafny-lang/dafny/releases/tag/v3.2.0). You'd only have to configure the extension to point to the installation locations of both binaries.

Further debugging of the download process would probably require checking out the source code of the extension and running it in debug mode. Therefore, I hope the manual installation is an acceptable solution for you.

**Comment by Aaron-clou** [comment]
I solved it  manually by installing Dafny3.2.0  ,thanks a lot

**Comment by camrein** [comment]
Since you managed to install Dafny manually, I'll close the issue for now. The next Dafny VSCode iteration will include a installation log for easier troubleshooting (e.g., slow download speed):
![Installation](https://user-images.githubusercontent.com/18049310/133434183-e3cb29b2-3df7-4010-825a-49c2f38a568f.png)
