### ISSUE TITLE
No verification status

### ISSUE THREAD

**Issue by Dargones** [dafny-lang/ide-vscode#39]
This might already have been addressed but starting with [#1307](https://github.com/dafny-lang/dafny/pull/1307) in Dafny repo, VS Code plugin doesn't show verification status. Is there a way to fix this and\or make a new release? I also have to restart VS Code sometimes to start verifying again although I haven't pinpointed the root cause of this yet. And thank you so much for keeping all of this running!

**Comment by camrein** [comment]
I've done my tests, and I believe that we're ready for a release. But, unfortunately, I've lost my permissions when moving the *ide-vscode* repository to the *dafny-lang* organization; thus, I have to wait until I get access again.

@RustanLeino could you please grant me *Admin* access to this repository as you once did for *language-server-csharp*? You'll find this option under *Settings* -> *Manage access*.

**Comment by camrein** [comment]
I've released v1.8.0 on the marketplace. This version provides the forward compatibility for the new status messages.
