### ISSUE TITLE
Identifiers with Underscores Cause Display Issues in Hover Information

### ISSUE THREAD

**Issue by dmzimmerman** [dafny-lang/ide-vscode#400]
When identifiers have underscores in them in pairs around blocks of text (as one would write to _italicize_ something in Markdown, for example), those identifiers are not displayed properly in Dafny's hover information. For example, consider the following code:
```dafny
module ?0
{
  class Example
  {
    var '_?_a_?1_variable__example: int
    var '_?a?1_variable_example: int
    
    method invalidSpec()
      modifies `'_?_a_?1_variable__example, `'_?a?1_variable_example
      ensures '_?_a_?1_variable__example == 0
      ensures '_?a?1_variable_example == 0
    {
      '_?_a_?1_variable__example := 1;
      '_?a?1_variable_example := 0;
    }
  }
}
```
Clearly, one of my `ensures` can't be proven. In the IDE, the opening bracket of the method gets a red squiggle, and hovering over that squiggle displays the following:

<img width="627" alt="Screenshot 2023-06-23 at 09 48 00" src="https://github.com/dafny-lang/ide-vscode/assets/75249/cbe4cef6-129f-4439-8de3-9565fab32845">

Note that in the error description, the variable name is displayed as `'_?a?1_variable__example`, rather than the correct `'_?_a_?1_variable__example`. In this example, we happen to have variables named both of those things, so it's giving me bad information (at least partially).

I realize this particular example is somewhat contrived; I synthesized it because of issues I've seen while working with the output of a tool I'm working on, which generates Dafny code that has a lot of variable names with underscores in them. Another display issue I've seen, which I presume is related to the same text processing, is that large portions of the error descriptions in some popups end up being italicized (and the variable names end up garbled, similar to what happened with the one above).

**Comment by dmzimmerman** [comment]
(I forgot to mention, this is with version 3.1.1 of the VSCode plugin)

**Comment by MikaelMayer** [comment]
Related to https://github.com/dafny-lang/dafny/issues/3686
Fixed by https://github.com/dafny-lang/dafny/pull/3687 that was merged 2 days ago ! Hurray ! If you use the latest nightly Dafny release, you should already see this change (in VSCode, select Dafny version, at the end of the list)
