### ISSUE TITLE
How to disable info squiggle underlines

### ISSUE THREAD

**Issue by locriacyber** [dafny-lang/ide-vscode#42]
In VS Code, info messages are marked like errors, albeit with a different color. Is there a way to turn them off?

It's hard to tell the color in some color themes, plus it's visual noise.

![screenshot](https://user-images.githubusercontent.com/74560659/131967513-f7acadac-0aec-4add-9ab2-39936889eab4.png)

**Comment by keyboardDrummer** [comment]
Have you tried configuring VSCode to remove the squiggles? https://stackoverflow.com/a/48610661/93197

**Comment by camrein** [comment]
Closing the issue as the severity of these messages will be reduced with the next Dafny release: https://github.com/dafny-lang/dafny/pull/1432
