### ISSUE TITLE
Cannot disable downloading precompiled Dafny

### ISSUE THREAD

**Issue by tchajed** [dafny-lang/ide-vscode#422]
I'm on an Apple Silicon mac. I wanted to use Dafny through Docker, which is Linux on arm64, and the extension fails to set up Dafny because this isn't a platform that Dafny provides a binary release for. I have Dafny compiled within this Docker image, but I don't know how to direct the extension to use this local copy.

The README mentions `dafny.languageServerRuntimePath` but it isn't actually used by the extension.

I also tried setting the Dafny version to "custom" but then it just tries to install a URL that includes `vcustom` so I suspect this feature is buggy.

**Comment by furioncycle** [comment]
I actually was running into this, when I was wanting to package the extension in nixpkgs. 

I was able to pull the extension but errors due to try to make a directory for the compiler to be downloaded. I tried to use the user settings but it seemed it was ignored and still tried to download a compiler.

**Comment by keyboardDrummer** [comment]
If you set the version to custom:
<img width="514" alt="image" src="https://github.com/dafny-lang/ide-vscode/assets/3121201/acb935d7-eef2-4fb8-b80e-16912133a7ad">
And configure a CLI path:
<img width="1252" alt="image" src="https://github.com/dafny-lang/ide-vscode/assets/3121201/d5b078d8-92b7-46c7-9a77-a2a951ca2a5d">
Then the extension will use the Dafny executable that you've pointed to.

**Comment by keyboardDrummer** [comment]
> The README mentions dafny.languageServerRuntimePath but it isn't actually used by the extension.

I couldn't find that. Could you point me to where that is written @tchajed ?

**Comment by furioncycle** [comment]
Adding custom worked to my user settings and adding dafny bin but I seem to now get the following 

`Dafny Language Server client: couldn't create connection to server.
Launching server using command /tmp/vscode-dafny-dlls-0969fE/dafny failed. Error: spawn /tmp/vscode-dafny-dlls-0969fE/dafny ENOENT` 

Do you know why this might be the case?

**Comment by keyboardDrummer** [comment]
> Error: spawn /tmp/vscode-dafny-dlls-0969fE/dafny ENOENT

Indicates that node could not find the executable file `/tmp/vscode-dafny-dlls-0969fE/dafny`. Is that file there?

Here's a thread about this type of error: https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

What operating system are you on?

**Comment by keyboardDrummer** [comment]
> > 
> 
> I noticed that folder location is made in my vscode workspace. Why would it need to spawn that?

That is meant to make it easier to use a Dafny built from source using the custom option. By copying the binary to a fresh location before running it, the binary can be rebuilt while VSCode is using the copy. 

@MikaelMayer I'm not a big fan of this approach. I use the `DAFNY_DEV_SERVER` environment variable instead of custom when running against builds from source, which doesn't do the copying anyways. Do you think we could remove the copying for the 'custom' option?

**Comment by RiscadoA** [comment]
> > > Error: spawn /tmp/vscode-dafny-dlls-0969fE/dafny ENOENT
> > 
> > 
> > Indicates that node could not find the executable file `/tmp/vscode-dafny-dlls-0969fE/dafny`. Is that file there?
> > Here's a thread about this type of error: https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js
> > What operating system are you on?
> 
> I noticed that folder location is made in my vscode workspace. Why would it need to spawn that?
> 
> I am running Nixos

I had the exact same problem, also on NixOS. After reading the extension's source code I managed to find the source of the error - take a look at #502. A bit off topic to the actual issue here, but there might be other people with the same issue.

**Comment by keyboardDrummer** [comment]
Closing this since I think the two underlying issues (lack of documentation and in-extension hints), and an incorrect file filter, are resolved.
