### ISSUE TITLE
Rename publisher from "correctnessLab" to "dafny-lang" or similar

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/ide-vscode#43]
Especially since the source now lives under `dafny-lang`, this would be a nice bit of polish.

Unfortunately there's no facility to automatically redirect from an old name to a new name for a package, so this will have to be done by deprecating the old name and manually redirecting users to the new name. 

@RustanLeino and I agree the start of the fall term is a terrible time to mess with this, so probably best to wait a couple of months. :)

**Comment by camrein** [comment]
I've already been mailing Rustan about this in some more detail. It's possible to change the publisher name and as you guessed, cannot change the unique identifier *correctnessLab.dafny-vscode*.
For "changing" the unique identifier, we have to create a suitable marketplace publisher with the desired identifier. Furthermore, if I remember correctly, an Azure Devops organization with the same identifier/name is necessary to automize the publish process. I believe it's best if Rustan created these. Although, it has gotten better in most places. Sometimes it's not possible to transfer the full ownership to another person. It appears to me that this is fine for the marketplace, but I don't know about Azure Devops.
