### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/ide-vscode#433]
Steps to reproduce the issue
----------------------------

* Dafny version: 4.2.0.0
* Dafny VSCode extension version: 3.1.2

Actual behavior
---------------

At the bottom of the screen, it says "Could not prove the declaration". It's confusing what "the declaration" refers to. Can we add a name or description of the declaration?

**Comment by keyboardDrummer** [comment]
Resolved in https://github.com/dafny-lang/ide-vscode/pull/432
