### ISSUE TITLE
Dafny extension does not start

### ISSUE THREAD

**Issue by hath995** [dafny-lang/ide-vscode#441]
In the output tab the following is printed.
```
Language server: {"command":"C:\\Program Files\\dotnet\\dotnet.exe","args":["c:\\Users\\Aaron-pc\\.vscode\\extensions\\dafny-lang.ide-vscode-3.2.0\\out\\resources\\4.3.0\\github\\dafny\\Dafny.dll","server","--verify-on:Change","--verification-time-limit:200","--cache-verification=0","--cores:1","--notify-ghostness:true","--notify-line-verification-status:true"]}
```
No other behavior is noticeable. The Dafny gutter and status bar do not appear. Running on Windows 10. I attempted to reinstall the plugin and dotnet but still nothing happens. Running latest dafny and older version do not seem to affect the result. 

VS-Code version
```
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

**Comment by keyboardDrummer** [comment]
Could you try running `C:\\Program Files\\dotnet\\dotnet.exe c:\\Users\\Aaron-pc\\.vscode\\extensions\\dafny-lang.ide-vscode-3.2.0\\out\\resources\\4.3.0\\github\\dafny\\Dafny.dll server --help` locally? 

And `C:\\Program Files\\dotnet\\dotnet.exe c:\\Users\\Aaron-pc\\.vscode\\extensions\\dafny-lang.ide-vscode-3.2.0\\out\\resources\\4.3.0\\github\\dafny\\Dafny.dll server` (it should not print any output but wait for input)

**Comment by hath995** [comment]
Running those commands "properly quoted" seem to run the correct behavior. However, Dafny is not starting in VS Code still. 

I noticed in the terminal tab there is an option to click on the "Dafny Language Server". 

The following is written:
```
The language client requires VS Code version ^1.82.0 but received version 1.80.1
```

Which is probably the cause. I was unaware of this version requirement. I keep clicking the "check for updates" menu item but VSCode doesn't seem to be updating.

**Comment by hath995** [comment]
Reinstalling has resolved the issue. Sorry, it seems my vscode installation was bad somehow.

**Comment by keyboardDrummer** [comment]
> Sorry, it seems my vscode installation was bad somehow.

No worries.
