### ISSUE TITLE
Type information on hover

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#47]
I would like the IDE to return type information when I hover over functions, methods, variables, etc.

**Comment by camrein** [comment]
This is already available:
![image](https://user-images.githubusercontent.com/18049310/134626952-48fa6cfa-2be4-4662-8b04-a02e9bc98665.png)
![image](https://user-images.githubusercontent.com/18049310/134626995-494a1c84-3f54-4d4d-8f99-50dd65eca59c.png)

However, there might be situations where this information is missing. If that's the case, do you have an example? Or do you desire more information displayed than the one already present?

**Comment by seebees** [comment]
Hum, this is great. I don't get anything like this. I'm guessing that my plugin is not set up right.
What you are showing is exactly what I was looking for.

My guess is that my install is... messed up. Where is the output log? (so I can try and debug this)

**Comment by seebees** [comment]
Ok, so I tried your example, in my project, and it works.

But nothing in my project works :(

**Comment by seebees** [comment]
I'm not sure, but this may be some useful information:

```dafny
  method arrayEquals(x: array<int>, y:array<int>)
  {
    // Hover/Peek/Go to definition all work
    assert x != y;
  }

  datatype Blarg = Blarg {
    method arrayEquals(x: array<int>, y:array<int>)
    {
      // "No definition found for 'x'"
      assert x != y;
    }
  }```
  method arrayEquals(x: array<int>, y:array<int>)
  {
    // Hover/Peek/Go to definition all work
    assert x != y;
  }

  datatype Blarg = Blarg {
    method arrayEquals(x: array<int>, y:array<int>)
    {
      // "No definition found for 'x'"
      assert x != y;
    }
  }
```

**Comment by camrein** [comment]
Thanks for sharing your example code. As you've observed, the symbol resolution for `datatype` and its children is currently not supported. I'll take a look into adding support for this language feature.
