### ISSUE TITLE
Feature request: visual indicator of verification status of each proof obligation

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/ide-vscode#50]
I find one of the trickiest aspects of the plugin is distinguishing whether verification of a particular line has completed successfully, or whether verification just hasn't completed yet. Similarly, it's not obvious whether a red squiggly line is leftover from a previous verification run or not.

I propose having a small icon in the left border of the editor window (close to where breakpoint red circles appear for example) for every line that contains a proof obligation, such as assert statements, function/method invocations, loop invariants, etc. It would have at least three different states: a lovely green checkmark for "verified", a red X for a failed verification, and perhaps something like a clock indicating "verification pending". The main benefit is that all of them would reset to the third state as soon as verification starts, making it clear where the results are not yet certain.

This would offer affordance in the future for interacting with the verifier at a more granular level: right-clicking could give options like "verify just this line/method/etc." or "cancel this verification job".

**Comment by camrein** [comment]
> I find one of the trickiest aspects of the plugin is distinguishing whether verification of a particular line has completed successfully, or whether verification just hasn't completed yet. Similarly, it's not obvious whether a red squiggly line is leftover from a previous verification run or not.

I guess that you're already aware of this, but just for clarification as others might have a similar issue. At this time, the language server reports errors in an all-or-nothing fashion. There are no partial results reported to the extension. That means if there are errors they are either all outdated or actual. On the bottom left of VSCode, you have a small visual indicator of whether a verification is running, failed, or succeeded (later versions depict compilation issues too). However, it should be noted that always the whole document is being verified (i.e., all boogie programs), no matter if already a verification error has been found. At the current state, this probably makes little sense.

> I propose having a small icon in the left border of the editor window (close to where breakpoint red circles appear for example) for every line that contains a proof obligation, such as assert statements, function/method invocations, loop invariants, etc. It would have at least three different states: a lovely green checkmark for "verified", a red X for a failed verification, and perhaps something like a clock indicating "verification pending". The main benefit is that all of them would reset to the third state as soon as verification starts, making it clear where the results are not yet certain.

That sounds absolutely fantastic. This will require some enhancements to the language server. Maybe it makes sense to relax the *all-or-nothing principle* in the future when integrating this feature.

> This would offer affordance in the future for interacting with the verifier at a more granular level: right-clicking could give options like "verify just this line/method/etc." or "cancel this verification job".

That's definitely a great vision.

**Comment by seebees** [comment]
> I propose having a small icon in the left border of the editor window

Do you mean a gutter icon?
If so this could be the affordance for the verification focus I asked for in #74?

If we want to have a more granular verification,
then I would want another gutter icons for method/function et al
that would let verify _only_ this scope.

I think we are all talking about the same things right?
We should try and mock a picture.

**Comment by atomb** [comment]
[This PR](https://github.com/dafny-lang/dafny/pull/1942) is a first step.

**Comment by MikaelMayer** [comment]
I think we have a lot of feedback of the verification status of each proof obligation now.
We don't have an icon for assertions that are pending though, but I think overall this issue was solved. Feel free to post a new issue for a new feature if you want to.
