### ISSUE TITLE
Lingering error messages

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/ide-vscode#501]
The error/warning messages reported for a file continue to show in the Problems pane after the file has been closed.

Repro:
* Open VS Code
* Open a `.dfy` file that contains error (or introduce errors in the file after opening it)
* Close the file
* The Problems pane still show the errors

![Screenshot 2024-10-03 at 14 37 22](https://github.com/user-attachments/assets/37e33813-b2da-4952-b2bd-251e409c8048)

**Comment by keyboardDrummer** [comment]
I can't reproduce this

**Comment by RustanLeino** [comment]
I can't reproduce now either.
