### ISSUE TITLE
How can a new version of this extension be published to the VSCode marketplace?

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/ide-vscode#51]
It might be nice if that is possible through GitHub Actions, as opposed to for example relying on personal credentials.

**Comment by camrein** [comment]
New versions are automatically published when pushing a tag starting with `v` to the master branch. See the `release-marketplace` job, especially the following line:
https://github.com/dafny-lang/ide-vscode/blob/929b0da1edc9e673a1c2dbe1309ed9e0f059c607/.github/workflows/ci.yaml#L127

The token is tied to a Marketplace account (currently mine) and expire after a year:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#get-a-personal-access-token

This morning I've sent an E-Mail to Rustan mentioning that I'd like to grant him and other Dafny team members the necessary access rights to the marketplace organization. Alternatively, we could create a new organization as suggested in #43. But I don't think that we can change the ownership of an already published extension (at least not the ID *correctnessLab.dafny-vscode*). Therefore we'd have to create a new release and motivate users to switch.
