### ISSUE TITLE
Is verification more like tests?

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#75]
I've been thinking about how long verification can take.
Rather than modeling it "part of the code"
perhaps it would be more efficient to treat it
as a more expensive process that can be explicitly run?

Then we could keep some local history and see what changed
between successful verification?

This could also give us an affordance for even more expensive operations.
Like debugging proofs or more extensive verifications to suggest ensures clauses?

**Comment by camrein** [comment]
I've noticed this issue as well. The automatic verification (that can be set to run only when saving a document or never) that we have now can become problematic if the verification takes long.
The PR https://github.com/dafny-lang/dafny/pull/1516 laid the foundation to support triggering the document verification manually. What's missing now is that the language server exposes an API to trigger the verification and implement it in the extension.
Do you have a suggestion about a keyboard shortcut that might be intuitive here? I've been thinking about `Ctrl+Shift+V` and `⇧+⌘+V` analog to the build shortcut with `B`.

**Comment by keyboardDrummer** [comment]
I think it would be nice to use the VSCode testing API ([ref](https://code.visualstudio.com/api/references/vscode-api#tests)) to visualise the verification status of each method. If you have automatic verification turned off, you could then use the UI to select what to verify, either one method, a group or all of them.

If we add parallel verification to Dafny, you could see multiple methods verifying in parallel and watch their status update to passed or failed one by one.

**Comment by camrein** [comment]
> I think it would be nice to use the VSCode testing API ([ref](https://code.visualstudio.com/api/references/vscode-api#tests)) to visualise the verification status of each method. If you have automatic verification turned off, you could then use the UI to select what to verify, either one method, a group or all of them.

That's an excellent proposal. This way we do not have to re-invent the wheel and think about how we can visualize these actions in an intuitive way. There's even an [introduction guide](https://code.visualstudio.com/api/extension-guides/testing) with an example extension showcasing the VSCode's Testing API.

**Comment by seebees** [comment]
Huge +1. We should also take a look at https://wallabyjs.com/ and https://quokkajs.com/.

Quokkajs would be a nice way to turn on "automatic verification".
They have quite a few tools that map onto similar ideas.
For example the way you can ask for console output or inspect a variable,
feels like it would be a nice way to interact with counter examples.

Wallaby, is a great product and they have put a LOT of work into making the tests fast.
I could see us using some of that to do caching.
For example we could make a cache that stores the Dafny => Boogie files such that you only need to do update diffs :)

**Comment by camrein** [comment]
Thanks a lot for this input. I've had some additional thoughts about #52. We could integrate the counterexamples with this testing approach. But we have to bear in mind that counterexamples provide information for every line/statement.

**Comment by robin-aws** [comment]
I'm hugely in favour of this approach - I had the same realization as @seebees at about the same time :) The `/verificationLogger:trx` option I added in 3.3 even fits nicely into the idea that verification can be thought of as executing a test suite with 100% coverage.

I've assigned @MikaelMayer to this as he has the capacity to start tackling it, and I feel this is really important to make the IDE experience more natural and responsive. We have a family of tightly related issues and ideas to untangle before we start the actual work though. I recall @keyboardDrummer had the suggestion of using the [Build Server Protocol](https://build-server-protocol.github.io/docs/specification) rather than the LSP interface for this - we should investigate that before we start extending the current language server for this purpose.

**Comment by MikaelMayer** [comment]
Thanks for mentioning me, how come I had missed this thread ! Of course, having an interactive summary of verification would totally make sense, especially to re-run the verification on one method only.
And we could still have the auto-running of the verification on the line/method the cursor is in, depending on user-specified parameters.
Let me assign me this issue. Oh, it seems like you already did it. Perfect.

**Comment by robin-aws** [comment]
I realized that we talked about this without me actually providing you the link. :)

**Comment by MikaelMayer** [comment]
With respect to the build server protocol, for now I suggest I only ensure that the "verification protocol" is built in into the LSE, possibly in a class of its own and follows conventions of the build server protocol.
That way, it's straightforward for now, and later the refactoring to make it a true build server protocol shouldn't be that hard.
Thanks for suggestion.

**Comment by seebees** [comment]
Can this be closed?

**Comment by keyboardDrummer** [comment]
Closing since this is resolved by https://github.com/dafny-lang/ide-vscode/pull/229
