### ISSUE TITLE
Promise.any is not a function

### ISSUE THREAD

**Issue by UnknownGuardian** [dafny-lang/ide-vscode#80]
![image](https://user-images.githubusercontent.com/239155/141031818-565b9a2e-37f4-44d8-b6d6-7225347f8886.png)

With v2.0.0, the extension seems to fail to load - the Dafny Language Server doesn't appear to start. This happens when a custom DafnyLanguageServer.dll is specified and when the default one is used.

By seems to fail to load, I mean that the Verification Succeeded/Failed message doesn't show up in the status bar, using the F7-9 commands doesn't work and it says command X not found. Reverting  back to 1.8.0 fixes this issue and the extension works normally.

**Comment by camrein** [comment]
Thanks a lot for reporting the issue. Which VSCode version are you using? Unfortunately, older VSCode versions have a node packaged that does not support `Promise.any` yet. I thought I've caught the minimum required version, but it appears that it's not sufficient.

**Comment by UnknownGuardian** [comment]
![image](https://user-images.githubusercontent.com/239155/141066251-241616bb-2411-465e-825b-8964ec968c2c.png)
Its the most recent version of VS Code as far as I can tell.

**Comment by UnknownGuardian** [comment]
Some further info here:
It looks like vscode's [current electron version](https://github.com/microsoft/vscode/blob/main/.yarnrc#L2) is 13.5.2, which [corresponds Nodejs version](https://github.com/electron/releases#releases) 14.16.0. To get NodeJS 15, which has the Promise.any(), you'll have to wait for Electron v15 which ships with Node v16
