### ISSUE TITLE
Spellchecking in Dafny files

### ISSUE THREAD

**Issue by seebees** [dafny-lang/ide-vscode#86]
I use https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
because I am an atroshous speller :)

However, in Dafny source files, especially comments, it does not appear to work.

**Comment by camrein** [comment]
The extension is only enabled for a [selection of languages](https://github.com/streetsidesoftware/vscode-spell-checker#enabled-file-types) by default.
You can enable the spell checking for a specific file or all Dafny files using the [toolbar entry](https://github.com/streetsidesoftware/vscode-spell-checker#enable--disable-file-types):
![image](https://user-images.githubusercontent.com/18049310/142375744-d816ed4c-5c5e-4caa-97b2-73b425fdcf0b.png)
Then tick the large box behind *File Type: dafny*:
![image](https://user-images.githubusercontent.com/18049310/142375928-5dd11142-80ce-41ec-8181-7c9b48e3a1ee.png)

**Comment by seebees** [comment]
Sweet. Thanks
