### ISSUE TITLE
Runaway Z3 processes

### ISSUE THREAD

**Issue by audreyseo** [dafny-lang/ide-vscode#95]
When using the Dafny VS Code extension on macos (version v2.0.2), if I add enough difficult to verify invariants/assertions to code I'm trying to verify, it makes the verifier hang for forever. Additionally, the multiple z3 processes that are run by the verifier are not killed once they start hanging, even if I quit VS Code.

<img width="639" alt="VS Code is not open, but there are 4 Z3 processes that are continuing to run" src="https://user-images.githubusercontent.com/14080871/144909835-ae122a44-8394-4723-8956-10989f0714ff.png">

This apparently does not have to do with Dafny itself on my machine, since the Emacs mode works just fine. (The Emacs mode for Dafny also has a default timeout of 20 seconds. Would it be possible to add a timeout for the verification? This might resolve this issue. I'd be happy to submit a separate issue for adding that feature.)

(This is with the caveat that if it continues to try to verify without success in VS Code, trying to verify from the command line may also run for forever. But at least when I interrupt the command line process, the corresponding Z3 process(es) do not stick around afterwards.)

Thanks! Let me know if any additional information is needed.

**Comment by camrein** [comment]
Thanks for reporting this issue. It is related to https://github.com/dafny-lang/dafny/issues/1611.

> since the Emacs mode works just fine

Does Emacs spawn multiple Z3 processes or just a single one? You could configure VSCode to just use a single process to see if that resolves this issue for the moment.

> Would it be possible to add a timeout for the verification?

Besides the use of multiple cores, the release v2.0.0 added the option to configure a verification time limit. See VSCodes option page, for example:
![image](https://user-images.githubusercontent.com/18049310/145053777-ec95a872-a145-4086-933b-5b2e336254d4.png)

**Comment by keyboardDrummer** [comment]
When closing a Dafny file, VSCode's LSP client sends a cancel request. It doesn't seem to cause a verification cancellation in the Dafny LSP server.

```
[Trace - 4:35:45 PM] Sending notification '$/cancelRequest'.
Params: {
    "id": 12
}
```

No LSP shutdown event is sent from VSCode when all Dafny files are closed.

**Comment by camrein** [comment]
Thanks for your input and sharing your observations.

> When closing a Dafny file, VSCode's LSP client sends a cancel request. It doesn't seem to cause a cancellation of verification in the Dafny LSP server.

I guess this will be relevant if a request (for example hover) is sent while the document is being processed. This case is not handled yet in the language server. For example, see the `Handle` method of [DafnyHoverHandler](https://github.com/dafny-lang/dafny/blob/c7792c2a430f573533960631d973ecc55d4d9a45/Source/DafnyLanguageServer/Handlers/DafnyHoverHandler.cs#L27). The `cancellationToken` is not used anywhere yet. However, with the merge of https://github.com/dafny-lang/dafny/pull/1456 it now makes sense to support the cancellation of these requests.

**Comment by audreyseo** [comment]
> Thanks for reporting this issue. It is related to [dafny-lang/dafny#1611](https://github.com/dafny-lang/dafny/issues/1611).
> 
> > since the Emacs mode works just fine
> 
> Does Emacs spawn multiple Z3 processes or just a single one? You could configure VSCode to just use a single process to see if that resolves this issue for the moment.

Emacs spawns a single one. Is the option to use the virtual cores option? Or is there somewhere else to configure this?

> 
> > Would it be possible to add a timeout for the verification?
> 
> Besides the use of multiple cores, the release v2.0.0 added the option to configure a verification time limit. See VSCodes option page, for example: ![image](https://user-images.githubusercontent.com/18049310/145053777-ec95a872-a145-4086-933b-5b2e336254d4.png)

Oops, I completely missed that in the options, I’m not typically a VS Code user and was only using it for a class that recommended the vs code extension. I’ll check that out and report back, thanks!

**Comment by keyboardDrummer** [comment]
Seems like the Dafny language server stays running when VSCode is closed, even if no z3 process is running:
```
|--- 83025 rwillems /usr/local/Cellar/dotnet/5.0.207/libexec/dotnet /Users/rwillems/.vscode/extensions/correctnesslab.dafny-vscode-2.0.2/out/resources/dafny/DafnyLanguageServer.dll --documents:verify=onchange --verifier:timelimit=0 --verifi
```

**Comment by keyboardDrummer** [comment]
Sending a TERM signal to the language server closes it:
```
rwillems@3c22fbe526e6 Binaries % ps 01767
  PID   TT  STAT      TIME COMMAND
 1767   ??  S      0:30.60 /usr/local/Cellar/dotnet/5.0.207/libexec/dotnet /Users/rwillems/.vscode/extensions/correctnesslab.dafny-vscode-2.0.2/out/resources/dafny/DafnyLanguageServer.dll --documents:verify=onchange --verifier:timelimit=0 --verifier:vcscores=0
rwillems@3c22fbe526e6 Binaries % kill -s TERM 01767
rwillems@3c22fbe526e6 Binaries % ps 01767    
```

And the Dafny VSCode extension seems to try and shut down the language server when VSCode is closed: https://github.com/dafny-lang/ide-vscode/blob/master/src/extension.ts#L28

**Comment by keyboardDrummer** [comment]
The C# LSP language server has some logic for handling parent process shutdowns: https://github.com/OmniSharp/omnisharp-roslyn/blob/master/src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs#L146

Seems indeed like killing the parent of the language server doesn't kill the language server:
```
rwillems@3c22fbe526e6 dafny % node -e "require('child_process').execFileSync('/Users/rwillems/Documents/SourceCode/dafny/Binaries/DafnyLanguageServer')" &
[1] 13169
rwillems@3c22fbe526e6 dafny % pstree 13169
-+= 13169 rwillems node -e require('child_process').execFileSync('/Users/rwillems/Documents/SourceCode/dafny/Binaries/DafnyLanguageServer')
 \--- 13170 rwillems /Users/rwillems/Documents/SourceCode/dafny/Binaries/DafnyLanguageServer
rwillems@3c22fbe526e6 dafny % kill -s TERM 13169
rwillems@3c22fbe526e6 dafny % 
[1]  + terminated  node -e 
rwillems@3c22fbe526e6 dafny % pstree 13170
--- 13170 rwillems /Users/rwillems/Documents/SourceCode/dafny/Binaries/DafnyLanguageServer
```

**Comment by keyboardDrummer** [comment]
@camrein I'll try to resolve this but it might take a little bit before I can make time for it.

**Comment by camrein** [comment]
> @camrein I'll try to resolve this but it might take a little bit before I can make time for it.

Thanks a lot. This month is quite busy for me, but I'll try to help where I can. I have the feeling that it might be related to #76.
