### ISSUE TITLE
Allow cancelling the verification of a proof

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/ide-vscode#96]
Given a proof that is currently verifying, allow customers to cancel that verification. 

Example use-cases:
- A customer has two Dafny files open and has not defined a Dafny project. When the customers edits both files sequentially, the IDE will concurrently start verification of both files. The customer then decides they only want to continue working on one file and cancels the verification of the other file to free up resources.
- A customer changes a utility function that is used by a 100 methods, and has configured automatic verification so that these methods also start to be verified. However, after 10 of the 100 methods have successfully verified, the customer trusts the others will verify as well, and cancels the verification to free up resources for verifying other things they're working on.
- A customer opens an open source Dafny project, and manually starts the verification of a particular method to see if it verifies, but then decides the verification it taking too long and cancels it to free up resources.

### Prerequisites

- UI for showing which proofs are currently being verified. As part of this, we expect that Boogie's `InferAndVerify` returns a list of `ProofExecution` objects that have an identifier, and that have a `Task` field.
- https://github.com/dafny-lang/dafny/issues/1647, which exposes proofs that are being verified as an `IDictionary<Proof, Task>` object.

### Implementation suggestion

- Update a `ProofExecution` so it allows cancelling the `Task` that it contains.
- Add a new message type to allow the client to communicate to the server that it wants to cancel a running verification. A verification can be identified by an ID that was passed to the client as part of a verification discovery message.
- Update the client so it has additional UX to allow cancellation something that's verifying. This will likely be adding an additional item to a context menu.

**Comment by MikaelMayer** [comment]
This will be even easier to implement with https://github.com/boogie-org/boogie/pull/491
Basically, we will be able to just invoke the regular ExecutionEngine.CancelRequest(requestId) and it will now take care of stopping the prover, which was not the case before.

**Comment by keyboardDrummer** [comment]
Closing because this feature is already available
